#!/bin/bash
read -a words < list
declare -A counts
for word in "${words[@]}"; do
	(( counts[$word]++ ))
done
for word on "${!counts[@]}"; do
	if (( counts[$word] == 1 )); then
		echo "$word"
	fi
done | sort
